# Site settings
title: Note
description: > # this means to ignore newlines until "baseurl:"
  Coding Note
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://sekitakuya.github.io" # the base hostname & protocol for your site
github_username:  SekiTakuya

# Build settings
markdown: kramdown
